name: Deploy 🏗️

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      commit:
        required: false
        type: string
      comment:
        required: false
        type: boolean
      artifact_name:
        required: false
        type: string
        default: frontend

jobs:
  github-pages:
    name: GitHub Pages 📃
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.branch == 'master' && 'Production' || 'Preview' }}
      url: ${{ steps.pages.outputs.page_url }}
    outputs:
      url: ${{ steps.pages.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download workflow artifact ⬇️
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
          path: dist

      - name: Deploy to GitHub Pages 📃
        id: pages
        uses: actions/deploy-pages@v1
        with:
          branch: ${{ inputs.branch }}
          folder: dist

  compose-comment:
    name: Compose and push comment 📝
    # Always run so the comment is composed for the workflow summary
    if: ${{ always() }}
    uses: ./.github/workflows/__job_messages.yml
    secrets: inherit
    needs:
      - github-pages

    with:
      branch: ${{ inputs.branch }}
      commit: ${{ inputs.commit }}
      preview_url: ${{ needs.github-pages.outputs.url }}
      in_progress: false
      comment: ${{ inputs.comment }}
